config/routes.rb
Rails.application.routes.draw do
  # get 'stripe/create'
  resources :charges, only: [:new, :create, :edit]
  resources :wikis
  devise_for :users
  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis, dependent: :destroy, through: :collaborators
  has_many :collaborators
  after_initialize {self.role ||= :standard }
  after_update :check_user_private_wiki

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
         # :validatable, :confirmable

  enum role: [:standard, :premium, :admin]

  def check_user_private_wiki
    if self.standard?
      Wiki.where(user_id: self.id, private: true).find_each do |wiki|
        wiki.update_attribute(:private, false)

      end
    end
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  attr_accessor :col_email
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  def initialize
    @col_email = col_email
  end
  # @w = Wiki.new
  # puts @w.attribute_names
  # before_save

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def user_not_authorized
    if current_user.present?
      flash[:alert] = "You are not authorized to perfom this action."
      redirect_to(wiki_path)
    else
      flash[:alert] = "You need to sign up to perfom this action."
      redirect_to(new_user_registration_path)
    end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: 1000,
      description: "BigMoney Membership - #{current_user.email}",
      currency: 'usd'
    )

    # If stripe transaction completes, charge is returned
    # charge.paid is a boolean on success of payment processing
    current_user.update_attribute(:role, "premium") if charge.paid?

    #puts current_user.role

      flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again. "
      redirect_to new_charge_path(current_user)

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership = #{current_user.email}",
      amount: 1000
    }
  end

  # downgrades user account when hitting this page.
  # not a great solution since someone can just type
  # the page link and downgrade the account
  def edit
    user = current_user
    user.update_attribute(:role, "standard")
    
  end
end

app/controllers/collaborator_controller.rb
class CollaboratorsController < ApplicationController

  def new
    @collaborator = Collaborator.new
  end

  def create
    #@wiki_id = Wiki.find(params[:wiki_id])
# user_id is from input user, not current user
    #@user_id = User.find(params[:user_id])
    @collaborator = Collaborator.new
    # @collaborator.user_id =
    # @collaborator.wiki_id =
    # @collaborator.email =
  end

  def edit
    @collaborator = colaborators.build(collaborator_params)
  end

  def update
    @collaborator = colaborators.build(collaborator_params)
  end

  private

  def collaborator_params
    params.require(:collaborator).permit(:wiki_id, :user_id)

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  before_action :find_id, only: [:show, :edit, :update, :destroy]
  #after_action :show_coll, only: [:edit]
  # before_action :add_collaborator, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_user, only: :show
  #before_action :find_collaborators, only: :show

  # before_action :authorize @wiki

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    authorize @wiki
    # @user.wikis << Wiki.find(wiki_id)
    # @wiki.users << User.find(current_user)
  end

  def new

    @wiki = Wiki.new
    # @user = @wiki.users
    # @collab = @wiki.collaborators
    # puts @wiki.collaborators.empty?
    # puts @users
    #@wiki.collaborators = collaborators
    #puts @wiki.users
    # @user = @wiki.users
    # authorize @wiki
    # puts 'hello'
    #puts @wiki.users.find(2)
    #@wiki.users = users
    #@wiki.collaborators = collaborators
  end

  def create

    @wiki = current_user.wikis.new(wiki_params)
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to [@wiki]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    authorize @wiki

    # @wiki = Wiki.new
    # @wiki.col_email = "help@me.com"
    # @wiki.col_email = col_email
  end

  def update
    puts "b"
    puts @wiki.col_email
    puts @wiki.title
    puts @wiki.users.exists?(@wiki.col_email)
    # puts @wiki.users.find(email: :col_email)

    puts @wiki.attribute_names
    puts params[:f][:user_ids]
    puts @wiki.private
    puts "a"

    if @wiki.update_attributes(wiki_params)
      puts @wiki.title
      puts :why
      puts @col_email
      flash[:notice] = "Wiki was updated"
      redirect_to [@wiki]
    else
      flash.now[:alert] = "There was an error updating the post. Please try again."
      render :edit
    end
  end

  def destroy
    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title} \" was deleted."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private

  def wiki_params
    puts "params here"
    params.require(:wiki).permit(:title, :body, :private, :user_ids, :col_email)
  end

  def find_id
    @wiki = Wiki.find(params[:id])
    # @wiki.col_email = col_email
    # puts Wiki.attribute_names

  end

  def find_user
    @user = User.find(@wiki.user_id)
  end

  def add_collaborator
    @collab = []
    @collab = Collaborator.where(:wiki_id => @wiki.id)
  end

  def show_coll
    puts params[:f][:user_ids]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  require 'redcarpet/render_strip'

  def markdown(text)
    extensions = {
      no_intra_emphasis: true,
      tables: true,
      fenced_code_blocks:true,
      autolink: true,
      # disable_indented_code_blocks: true,
      strikethrough: true,
      lax_spacing: true,
      # space_after_headers: true,
      superscript: true,
      underline: true,
      highlight: true,
      quote: true,
      footnotes: true,
    }

    options = {
      # filter_html: true,
      # no_images: true,
      # no_links: true,
      # no_styles: true,
      # escape_html: true,
      # safe_links_only: true,
      # with_toc_data: true,
      # hard_wrap: true,
      # xhtml: true,
      # prettify: true,
      # link_attributes: true,
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(text).html_safe
  end

  def hide_markdown_format(text)
    renderer_remove = Redcarpet::Render::StripDown
    remove_markdown = Redcarpet::Markdown.new(renderer_remove)
    remove_markdown.render(text)
  end
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/edit.html.erb
<h2>Your account has been downgraded to Standard</h2>

<h4>You will no longer be able to post a private Wiki.</h4>
<h4>Your existing private Wiki are now public.</h4>


<h3>Upgrade to Premium</h3>
<%= link_to "Upgrade", new_charge_path, class: 'btn btn-success' %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Itstrue</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Itstrue", welcome_index_path %></li>
      <li><%= link_to "About", welcome_about_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>
    </ul>

    <% if user_signed_in? %>
      Signed in as: <strong><%= current_user.email %></strong> |
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
      <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/wikis/_new_collaborator.html.erb
<#%= form_for(@wiki.users) do |ff| %>
  <% @wiki.users.each_with_index do |c| %>
    <%= f.label c.email %>
    <small><%= c.email %> </small>
  <% end %>
  <@%= ff.label :email %>
  <@%= ff.email_field @wiki.edit.col_email %>
  <div class="actions">
    <#%= ff.submit %>
  </div>
<#% end %>

app/views/wikis/create.html.erb
<h1>Wikis#create</h1>
<p>Find me in app/views/wikis/create.html.erb</p>

app/views/wikis/destroy.html.erb
<h1>Wikis#destroy</h1>
<p>Find me in app/views/wikis/destroy.html.erb</p>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
<%= form_for(@wiki) do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%puts @wiki.body%>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :private %><br>
    <%= f.check_box :private %>
  </div>
  <#%= render partial: 'new_collaborator' %>
  <div class="field">
    <%= f.label "Add or remove a collaborator" %><br>
    <%= f.email_field :col_email, placeholder: "User name (email)" %>
  </div>
  <div>


    <h4>Current Collaborators</h4>
    <% @wiki.users.each do |c| %>
      <div class="field">
        <%= check_box_tag "f[user_ids][]", c.id, @wiki.user_ids.include?(c.id) %>
        <small><%= c.id %> <%= c.email %> </small></br>
      </div>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end%>

<%= link_to 'Back', wikis_path %>

app/views/wikis/index.html.erb
<h1>Current Wikis</h1>
<div class="row">
  <div class="col-md-8">
    <% @wikis.each do |w| %>
      <% if !w.private? || (w.private? && !current_user.standard?) %>
        <div class="media">
          <div class="media-body">

              <h4 class="media-heading"><%= link_to w.title, w %></h4>
              <small><%=  %></small>
              <small><%= hide_markdown_format(w.body) %></small>
              <small>User name : <%= w.user_id %> | <%= w.private %></small>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
<%= form_for [@wiki] do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <% if current_user.admin? || current_user.premium? %>
    <div class="field">
      <%= f.label :private %><br>
      <%= f.check_box :private %> Private wiki
    </div>
    <div class="field">
      <%= f.label "Add a collaborator" %><br>
      <%= f.email_field :col_email, placeholder: "User name (email)" %>
    </div>
  <%end%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end%>

<%= link_to 'Back', wikis_path %>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>
<div class="row">
  <div class="col-md-8">
    <div class="media">
      <div class="media-body">
        <p><%= markdown(@wiki.body) %></p>
      </div>
      <small>User name : <%= @user.email %> | <%= @wiki.private %></small>
      <div>
        <h4>Collaborators</h4>
        <% @wiki.collaborators.each do |col| %>
          <small> <%= @wiki.users.find(col.user_id).email %> </br></small>
        <% end %>

      </div>

    </div>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path, class: 'btn btn-success' %>
    <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger' %>
    <%= render partial: 'new_collaborator', locals: {collaborator}
  </div>

</div>

app/views/wikis/update.html.erb
<h1>Wikis#update</h1>
<p>Find me in app/views/wikis/update.html.erb</p>